### PR TITLE
chore(sequelize): setup sequelize

### PR DESCRIPTION
**Pull request by tersoo-atsen**
#### What does this PR do?
Setups sequelize with postgres for the project
#### Description of Task to be completed?
- modified linting config
- setup sequelize
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#[161303559](https://www.pivotaltracker.com/n/projects/2205724/stories/161303559)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Comment by sulenchy** [comment]
Good one, man. But I have a concern about the description of the PR. It should not be a summary of the files changed. It should be a description of each of the files changed.

**Comment by KvNGCzA** [comment]
I think Abiodun is right about the description and there is still es5 in the .sequelizerc file.

**Review by darthrighteous — CHANGES_REQUESTED** [review]
This looks nice! The .sequelizerc and server/config/babelHook.js are still es5 though.

edit: I also just noticed that there are some rules turned off manually in the .eslintrc file which are already part of the airbnb-base.

**Comment by tersoo-atsen** [comment]
Thanks for your responses guys. 

I am not sure those 2 files can be refactored to ES6. Doing so breaks the sequelize setup.

**Comment by darthrighteous** [comment]
We should probably seek clarity about that. You remember when Victor asked about it during the sims on-boarding; he spoke about having to use extra plugins and stuff. So maybe theres a way to do it without breaking it.

**Comment by tersoo-atsen** [comment]
> Good one, man. But I have a concern about the description of the PR. It should not be a summary of the files changed. It should be a description of each of the files changed.

I am not sure I agree with this. Look [here](https://github.com/andela/engineering-playbook/tree/master/5.%20Developing/Conventions#pr-example), the description doesn't mention any files.

**Comment by tersoo-atsen** [comment]
> We should probably seek clarity about that. You remember when Victor asked about it during the sims on-boarding; he spoke about having to use extra plugins and stuff. So maybe theres a way to do it without breaking it.

I am presuming the extra pluggin he was referring to was babel, and more precisely a babel hook, which is what I am using already.

I may be wrong though and getting clarification might be the way to go.

**Comment by augustineezinwa** [comment]
Nice PR, but try to refactor all codes to ES6. Remember we are world class.

**Review by darthrighteous — APPROVED** [review]

**Pull request merged**
