### PR TITLE
#161321654 Initialize Npm

### PR DESCRIPTION
**Pull request by darthrighteous**
#### What does this PR do?
sets up npm, adds package.json, adds package-lock.json
#### Description of Task to be completed?
- run `npm init` 
#### How should this be manually tested?
n/a
#### Any background context you want to provide?
n/a
#### What are the relevant pivotal tracker stories?
[#161321654](https://www.pivotaltracker.com/story/show/161321654)

### CODE REVIEW

**Comment by sulenchy** [comment]
@Darthrighteous @mrSerious @KvNGCzA @augustineezinwa Nice one. But I think the description should be `Initialize npm

**Comment by augustineezinwa** [comment]
The relevant pivotal stories should be the id of the story, such as #161321654

**Review by KvNGCzA — APPROVED** [review]
Good job.

**Review by augustineezinwa — COMMENTED** [review]
PR titles should be capitalized. eg #161321654 Npm setup

**Review by sulenchy — COMMENTED** [review]
It is okay. you can go on merging it

**Comment by darthrighteous** [comment]
test comment

**Pull request merged**
